# Generated by Django 5.2.13 on 2026-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_data', models.JSONField()),
            ],
        ),
    ]
