# Generated by Django 5.2.13 on 2026-04-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='current_location',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='cycle_used_hours',
            new_name='cycleUsedHours',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='dropoff_location',
            new_name='dropoff',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='pickup_location',
            new_name='pickup',
        ),
    ]
